apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 4f179e39-c2fb-4ce5-8069-604661ab3cc9
  labels:
    cloud.googleapis.com/location: us-central1
  name: td-cr-prototype-sidecar
  namespace: '75445969589'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 430.0.0
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/network-testing-1-300022/locations/us-central1/connectors/serverlesscon
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/network-testing-1-300022/td-cr-prototype-sidecar:latest
        ports:
        - containerPort: 15000
          name: h2c
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 15000
          timeoutSeconds: 240
      serviceAccountName: 75445969589-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
