apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/operation-id: 4ad3b5fe-3406-4475-9c48-46db0af9fd8e
  labels:
    cloud.googleapis.com/location: us-central1
  name: td-cr-prototype-helloworld-mt
  namespace: '75445969589'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 430.0.0
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/network-testing-1-300022/locations/us-central1/connectors/serverlesscon
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/network-testing-1-300022/td-cr-prototype-sidecar:latest
        name: sidecar
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 230
          tcpSocket:
            port: 15001
          timeoutSeconds: 230
      - image: gcr.io/network-testing-1-300022/td-cr-prototype-helloworld:latest
        name: app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 75445969589-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
